In [2]:
import torch
import numpy as np
import torch.nn.functional as F

In [4]:
a = torch.randn(2, 3)
print(a)

# 方式1：打印出具体类型，在类型未知的时候测试使用
print(a.type())

# 方式2：打印出基本数据类型，用的比较少
print(type(a))

# 方法3：可以在代码里面使用，可以在运行时判断
print(isinstance(a, torch.FloatTensor))

tensor([[ 0.0152,  0.6306, -1.4532],
        [-0.0300,  0.5119,  2.4869]])
torch.FloatTensor
<class 'torch.Tensor'>
True


In [3]:
# 标量是维度为0的一种数据，常用于loss的计算
a = torch.tensor(2.2)
print(a)

print(a.shape)  # torch.Size([])
print(a.size())  # torch.Size([])
print(len(a.shape))  # 0
print(a.dim())

tensor(2.2000)
torch.Size([])
torch.Size([])
0
0


In [7]:
# 数学上的向量在torch里面对应为dim=1的张量，常用于bias、线性输入（例如minist输入 ）

# 创建方法
# 方法1
a = torch.tensor([1.1])  # 注意与标量的区别，多了个方括号
print(a)

b = torch.tensor([1.1, 2.2])
print(b)

# 方法2
c = torch.FloatTensor(1)  # 创建dim=1，size=1的张量，数据随即初始化
print(c)

d = torch.FloatTensor(2)  # 创建dim=1，size=2的张量，数据随即初始化

# 方法3：从numpy数组创建
e = np.ones(2)  # [1, 1]
f = torch.from_numpy(e)
print(f)

tensor([1.1000])
tensor([1.1000, 2.2000])
tensor([1.0005e-35])
tensor([1., 1.], dtype=torch.float64)


In [23]:
# shape size是一个概念，返回数据的形状
# dim指的是shape size的长度

x= torch.Tensor( [ [1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(x)
print(x.shape)
print(x.size())

sum1 = torch.sum(x, dim=0)
print(sum1)

sum2 = torch.sum(x, dim=1)
print(sum2)

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])
torch.Size([3, 4])
torch.Size([3, 4])
tensor([ 3.,  6.,  9., 12.])
tensor([10., 10., 10.])


In [24]:
# 类似于二维数组，一般第一个参数表示行，第二个参数表示列
# 常用于带batch的线性输入，比如（minist一批一批的输入网络计算，输入数据的shape=(batch, 784)）

a = torch.randn(2, 3)  # 随即正态分布初始化，均值=0，方差=1
print(a)
print(a.shape)
print(a.size())
print(a.size(0))
print(a.size(1))
print(a.shape[0])
print(a.shape[1])

tensor([[ 0.0048,  0.7965, -0.4765],
        [-0.5280,  0.4223,  0.9691]])
torch.Size([2, 3])
torch.Size([2, 3])
2
3
2
3


In [26]:
# 适用于RNN（例如NLP）中的输入，一个batch有好几个句子，每个句子有若干个单词，每个词语的编码为一个向量。

a = torch.rand(2, 2, 3)
print(a)
print(a.shape)
print(a[0])

print(list(a.shape))  # 使用list方法可以将torch.Size转换为list

tensor([[[0.1425, 0.9534, 0.1651],
         [0.6553, 0.7189, 0.0076]],

        [[0.3406, 0.2090, 0.9067],
         [0.9484, 0.6963, 0.2683]]])
torch.Size([2, 2, 3])
tensor([[0.1425, 0.9534, 0.1651],
        [0.6553, 0.7189, 0.0076]])
[2, 2, 3]


In [27]:
# 适用于图片数据，每一维度的含义可为[b, c, h, w]，分别表示batch、channels、高、宽，卷积神经网络

a = torch.rand(2, 3, 28, 28)
print(a)
print(a.shape)

tensor([[[[0.9312, 0.0136, 0.0178,  ..., 0.3117, 0.5709, 0.1713],
          [0.0254, 0.7644, 0.6051,  ..., 0.1637, 0.6827, 0.4928],
          [0.9121, 0.8322, 0.8782,  ..., 0.9809, 0.9352, 0.1766],
          ...,
          [0.9871, 0.5341, 0.9182,  ..., 0.9506, 0.5569, 0.0556],
          [0.5847, 0.3473, 0.0256,  ..., 0.3853, 0.6773, 0.8035],
          [0.5686, 0.6361, 0.1629,  ..., 0.1164, 0.2339, 0.7150]],

         [[0.7199, 0.6216, 0.9653,  ..., 0.9709, 0.6763, 0.6786],
          [0.6555, 0.1207, 0.3858,  ..., 0.7324, 0.2564, 0.2742],
          [0.9040, 0.2827, 0.1330,  ..., 0.1081, 0.1331, 0.9218],
          ...,
          [0.1757, 0.0150, 0.0302,  ..., 0.5074, 0.3985, 0.1627],
          [0.3826, 0.0591, 0.1541,  ..., 0.8584, 0.0321, 0.2121],
          [0.4710, 0.0416, 0.9362,  ..., 0.5718, 0.3223, 0.4632]],

         [[0.2044, 0.5810, 0.1560,  ..., 0.9827, 0.4054, 0.5388],
          [0.2784, 0.6796, 0.0178,  ..., 0.9461, 0.7456, 0.3379],
          [0.1303, 0.4869, 0.4616,  ..., 0

In [28]:
a = torch.rand(2, 3, 28, 28)
print(a.shape)
print(a.size())  # shape size()返回的是张量的形状

print(a.numel())  # 返回张量占用的内存空间大小，指的是数据的个数

print(a.dim())  # 返回数据的维度，维度形式上可以理解为方括号的个数

torch.Size([2, 3, 28, 28])
torch.Size([2, 3, 28, 28])
4704
4
