In [1]:
import torch
import numpy as np
import torch.nn.functional as F

In [3]:
# 方法1：import from numpy，numpy中数据类型是什么，导入后对应的数据类型也一样，只是加了torch
# 这种方式不会改变原来numpy的数据
a = np.array([2, 3.3])
b = torch.from_numpy(a)

print(a)
print(b)

a = np.ones([2, 3])
b = torch.from_numpy(a)

print(a)
print(b)

[2.  3.3]
tensor([2.0000, 3.3000], dtype=torch.float64)
[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# 方法2：import from list
# 一点建议：具体的小数据用a方式，暂时不明确的数据用这种方式

# 注意辨析，这个小写的api接收的是具体的数据，大写的torch.Tensor()接收的是数据的维度
a = torch.tensor([2., 3.2])

b = torch.FloatTensor([2., 3.2]) 

c = torch.tensor([[2., 3.2], [1., 4.2]])

print(a)
print(b)
print(c)

d = torch.Tensor(2, 3)  # torch.FloatTensor(r, c)
print(d)

tensor([2.0000, 3.2000])
tensor([2.0000, 3.2000])
tensor([[2.0000, 3.2000],
        [1.0000, 4.2000]])
tensor([[8.1379e-26, 4.5867e-41, 2.8209e-35],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [8]:
# 方法3：创建指定维度的空张量作为载体
# 创建未初始化的数据，这种方式创建的数据一定要赋值后才可以使用
# 1. torch.empty(d1, d2, d3)
# 2. torch.FloatTensor(d1, d2, d3)
# 3. torch.IntTensor(d1, d2, d3)

In [9]:
# 设置torch默认类型
# torch默认类型为torch.FloatTensor
# 可以使用torch.set_default_tensor_type(torch.DoubleTensor)改变默认数据类型

In [10]:
# 方法4：使用一些分布来创建张量
# 包括rand randn randint *_like等
a = torch.rand(3,3)  # 在[0, 1]之间服从均匀分布生成数据
print(a)

b = torch.rand_like(a)  # 读取a.shape，然后按照这个来创建张量
print(b)

c = torch.randint(1, 10, [3, 4])  # 在[min, max)之间均匀分布生成数据
print(c) 

tensor([[0.1681, 0.8865, 0.2597],
        [0.6423, 0.6844, 0.3210],
        [0.1603, 0.1387, 0.9617]])
tensor([[0.4585, 0.0234, 0.1930],
        [0.7693, 0.5786, 0.7558],
        [0.2174, 0.2154, 0.6182]])
tensor([[8, 6, 2, 8],
        [5, 6, 8, 8],
        [7, 3, 8, 9]])


In [12]:
# 方法5：使用torch.full() - 生成指定形状，值全部一样的张量
a = torch.full([2, 3], 7)
print(a) 

tensor([[7, 7, 7],
        [7, 7, 7]])


In [13]:
# 方法6：使用torch.arange(start, end, 间隔)
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 方法7：使用torch.linspace logspace 等
# 给定[start, end, steps]来生成数据，steps表示生成数据的个数，start end的值都可取
a = torch.linspace(0, -1, steps=10)
print(a)

b = torch.logspace(0, -1, steps=10)  # 对数据先按照torch.linspace()生成，然后取10的多少次方
print(b)

tensor([ 0.0000, -0.1111, -0.2222, -0.3333, -0.4444, -0.5556, -0.6667, -0.7778,
        -0.8889, -1.0000])
tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])


In [19]:
# 方法8：生成全为0、全为1，eye
# torch.ones(shape) torch.zeros(shape) torch.eye(shape)
torch.eye(2, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [21]:
# 方法9：torch.randperm()
# 使用场景：比如一个班的成绩包含语文、英文、数学，现在把人名、成绩shuffle了，
# 那么访问每个人的信息时也要注意索引一致，这样学习到的特征才是有效的
a = torch.randperm(10)  # [0, 10)
print(a, len(a))

tensor([6, 3, 5, 7, 0, 9, 2, 1, 8, 4]) 10
