In [1]:
import torch
import numpy as np

In [10]:
# 场景为：创建4张图片，每张图片3通道，height = 28 width=28
a = torch.rand(4, 3, 28, 28)  # 4维的数据，从左到右维度编号为 0 1 2 3
print(a.shape)

# 索引的方式为从左至右进行的，符合人的逻辑习惯
print(a[0])  # 返回第一张图片，shape为(3, 28, 28)
print(a[0, 0].shape)  # 返回第一张图片的第一个通道
print(a[0][0].shape)  # 同上

print(a[0, 0, 0])  # 返回第一张图片的第一个通道的第1行数据
print(a[0, 0, 0, 0])  # 返回第一张图片的第一个通道的第一行数据的第一个像素，是一个标量

torch.Size([4, 3, 28, 28])
tensor([[[0.9299, 0.5461, 0.5624,  ..., 0.7351, 0.1001, 0.4572],
         [0.6270, 0.1878, 0.5347,  ..., 0.0081, 0.3906, 0.7026],
         [0.5907, 0.1304, 0.6404,  ..., 0.1921, 0.2459, 0.4503],
         ...,
         [0.3599, 0.4308, 0.4100,  ..., 0.9777, 0.0744, 0.5989],
         [0.4599, 0.9585, 0.3300,  ..., 0.6833, 0.3023, 0.9542],
         [0.2539, 0.8836, 0.9347,  ..., 0.0294, 0.4686, 0.3718]],

        [[0.5841, 0.6189, 0.1983,  ..., 0.6680, 0.4102, 0.4493],
         [0.7472, 0.2380, 0.5879,  ..., 0.1348, 0.5814, 0.5411],
         [0.5143, 0.9561, 0.1302,  ..., 0.9910, 0.2828, 0.7035],
         ...,
         [0.9193, 0.8291, 0.8652,  ..., 0.3778, 0.4943, 0.5220],
         [0.6090, 0.0687, 0.5255,  ..., 0.5858, 0.8568, 0.5646],
         [0.4896, 0.0249, 0.0777,  ..., 0.6405, 0.9888, 0.6890]],

        [[0.9253, 0.3870, 0.7435,  ..., 0.4882, 0.4457, 0.7552],
         [0.9111, 0.1799, 0.0507,  ..., 0.1894, 0.0404, 0.0401],
         [0.8214, 0.0540, 0.878

In [26]:
a = torch.rand(4, 3, 6, 6)
print(a.shape)

b = a[:2]  # 读取前两张图片，冒号可以理解为箭头，默认从0开始，遵循左闭右开原则。如果冒号两边不写数字，则表示读取全部
print(b.shape)

c = a[:2, :1]  # 等同于a[:2, :1, :, :]，读取前两张图片的第一个通道的数据
print(c.shape)

d = a[:2, 1:]  # 读取前两张图片的后两个通道的数据
print(d.shape)

e = a[:2, -1:]  # 读取前两张图片的最后一个通道的数据
print(e.shape)

# 隔行采样
f = a[:2, : , ::2, ::2]  # 表示对前两张图片的所有通道的height width进行隔行采样
print(f.shape)

# select by specific index，指定某一维度按规则读取，其他维度不变
g = a.index_select(0,torch.tensor([0, 2]))  # 读取第一张和第三张图片，第二个参数必须是一个tensor
print(g.shape)

h = a.index_select(1, torch.tensor([0, 1]))  # 读取所有图片的第1 2通道
print(h.shape)

i = a.index_select(2, torch.arange(6))  # 读取第二维度从0 1 2 3 4 5的数据
print(i.shape)

j = a.index_select(2, torch.arange(4))  # 读取第二维度从0 1 2 3的数据
print(j.shape)

torch.Size([4, 3, 6, 6])
torch.Size([2, 3, 6, 6])
torch.Size([2, 1, 6, 6])
torch.Size([2, 2, 6, 6])
torch.Size([2, 1, 6, 6])
torch.Size([2, 3, 3, 3])
torch.Size([2, 3, 6, 6])
torch.Size([4, 2, 6, 6])
torch.Size([4, 3, 6, 6])
torch.Size([4, 3, 4, 6])


In [2]:
# 当 : 冒号很多时，写着就很麻烦，所以又有另一种方式来简写 ... 三个点来简写
# ... 根据张量的维度自动推测所代替的部分

a = torch.rand(4, 3, 28, 28)
print(a.shape)

b = a[...]
print(b.shape)

c = a[0, ...]
print(c.shape)

d = a[:, 1, ...]
print(d.shape)

e = a[..., :2]
print(e.shape)

torch.Size([4, 3, 28, 28])
torch.Size([4, 3, 28, 28])
torch.Size([3, 28, 28])
torch.Size([4, 28, 28])
torch.Size([4, 3, 28, 2])


In [3]:
# select by mask
# 用的比较少
x = torch.rand(3, 4)
print(x)

mask = x.ge(0.5)
print(mask)

a = torch.masked_select(x, mask)
print(a)

tensor([[0.6543, 0.2668, 0.6879, 0.6045],
        [0.1664, 0.6047, 0.8094, 0.1549],
        [0.7155, 0.2835, 0.3186, 0.9855]])
tensor([[ True, False,  True,  True],
        [False,  True,  True, False],
        [ True, False, False,  True]])
tensor([0.6543, 0.6879, 0.6045, 0.6047, 0.8094, 0.7155, 0.9855])
